import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/layout/header';
import FloatingContact from '@/components/layout/floating-contact';

export const metadata: Metadata = {
  title: '휴렌터카',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css"
        />
      </head>
      <body className="antialiased relative">
        <Header />
        <main className="w-full min-h-dvh">{children}</main>
        <FloatingContact />
      </body>
    </html>
  );
}
